# /etc/netplan/50-cloud-init.yaml
network:
    version: 2
    ethernets:
        ens3:
            dhcp4: true
            match:
                macaddress: fa:16:3e:0f:7c:6b
            set-name: ens3
        ens6:
            dhcp6: no
            addresses:
             - 2012::2/64
            routes:
              - to: 2001::/64
                via: 2012::1
        ens7:
            dhcp6: no
            addresses:
             - 2024::2/64
