#/etc/netplan/50-cloud-init.yaml
#Modify your interfaces
network:
    version: 2
    ethernets:
        ens3:
            dhcp4: true
            match:
                macaddress: fa:16:3e:39:64:c5
            set-name: ens3
        ens6:
            dhcp6: no
            addresses:
             - A::A/64
            gateway6: A::1
        ens7:
            dhcp6: no
            addresses:
             - 192.168.1.10/24
            routes:
              - to: 192.168.8.0/24
                via: 192.168.1.1
        ens8:
            dhcp6: no
            addresses:
             - A::C/64
            gateway6: A::1