# /etc/netplan/50-cloud-init.yaml
network:
    version: 2
    ethernets:
        ens3:
            dhcp4: true
            match:
                macaddress: fa:16:3e:5e:5d:40
            set-name: ens3
        ens6:
            dhcp6: no
            addresses:
             - 2067::7/64
        ens7:
            dhcp6: no
            addresses:
             - 2078::7/64
            routes:
              - to: 2008::/64
                via: 2078::8


